In [3]:
import numpy as np
import pandas as pd

In [4]:
from sklearn.model_selection import train_test_split,cross_val_score
from sklearn.tree import DecisionTreeClassifier

from sklearn.metrics import accuracy_score

from sklearn.compose import ColumnTransformer

In [12]:
df=pd.read_csv(r"C:\Users\DELL\Downloads\tested.csv")[['Age','Fare','SibSp','Parch','Survived']]

In [13]:
df.head()

    Age     Fare  SibSp  Parch  Survived
0  34.5   7.8292      0      0         0
1  47.0   7.0000      1      0         1
2  62.0   9.6875      0      0         0
3  27.0   8.6625      0      0         0
4  22.0  12.2875      1      1         1

In [14]:
df.dropna(inplace=True)

In [19]:
df.head()

    Age     Fare  SibSp  Parch  Survived  family
0  34.5   7.8292      0      0         0       0
1  47.0   7.0000      1      0         1       1
2  62.0   9.6875      0      0         0       0
3  27.0   8.6625      0      0         0       0
4  22.0  12.2875      1      1         1       2

In [17]:
df['family'] = df['SibSp'] + df['Parch']

In [18]:
df.head()

    Age     Fare  SibSp  Parch  Survived  family
0  34.5   7.8292      0      0         0       0
1  47.0   7.0000      1      0         1       1
2  62.0   9.6875      0      0         0       0
3  27.0   8.6625      0      0         0       0
4  22.0  12.2875      1      1         1       2

In [20]:
df.drop(columns=['SibSp','Parch'],inplace=True)

In [21]:
df.head()

    Age     Fare  Survived  family
0  34.5   7.8292         0       0
1  47.0   7.0000         1       1
2  62.0   9.6875         0       0
3  27.0   8.6625         0       0
4  22.0  12.2875         1       2

In [22]:
X = df.drop(columns=['Survived'])
y = df['Survived']

In [23]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [24]:
X_train.head()

       Age     Fare  family
281   0.75  13.7750       2
96   76.00  78.8500       1
341  32.00   7.5792       0
18   27.00   7.9250       1
26   22.00  61.9792       1

In [25]:
# Without binarization

clf = DecisionTreeClassifier()

clf.fit(X_train,y_train)

y_pred = clf.predict(X_test)

accuracy_score(y_test,y_pred)

0.5970149253731343

In [26]:
np.mean(cross_val_score(DecisionTreeClassifier(),X,y,cv=10,scoring='accuracy'))

np.float64(0.6074866310160428)

In [27]:
# Applying Binarization

from sklearn.preprocessing import Binarizer

In [28]:
trf = ColumnTransformer([
    ('bin',Binarizer(copy=False),['family'])
],remainder='passthrough')