In [1]:
import pandas as pd
import requests

In [11]:
url="https://pizza-and-desserts.p.rapidapi.com/pizzas"
headers={
    "x-rapidapi-key": "8abd7c1a66msh431697a773085c0p1f0cebjsn0a32ecf5fc15",
    "x-rapidapi-host": 'pizza-and-desserts.p.rapidapi.com' 

}

response=requests.get(url,headers=headers)
data=response.json()
df=pd.DataFrame(data)
df

,id,name,veg,price,description,quantity,img,sizeandcrust
0,1,Margherita,True,3,Cheese,1,https://api.pizzahut.io/v1/content/en-in/in-1/...,"[{'mediumPan': [{'price': 3}], 'mediumstuffedc..."
1,2,Tandoori Paneer,True,7,"Spiced paneeer, Onion,Green Capsicum & Red Pap...",1,https://api.pizzahut.io/v1/content/en-in/in-1/...,"[{'mediumPan': [{'price': 7}], 'mediumstuffedc..."
2,3,Veggie Supreme,True,8,"Black Olives,Green Capsicum, Mushroom, Onion,R...",1,https://api.pizzahut.io/v1/content/en-in/in-1/...,"[{'mediumPan': [{'price': 8}], 'mediumstuffedc..."
3,4,Double Paneer Supreme,True,6,"Spiced Paneer, Herbed Onion&Green Capsicum, Re...",1,https://api.pizzahut.io/v1/content/en-in/in-1/...,"[{'mediumPan': [{'price': 6}], 'mediumstuffedc..."
4,4,Veggie Kebab Surprise,True,4,"Veg Kebab,Onion,Green Capsicum,Tomato & Sweet ...",1,https://api.pizzahut.io/v1/content/en-in/in-1/...,"[{'mediumPan': [{'price': 5}], 'mediumstuffedc..."
5,5,Chicken Supreme,False,7,"Herbed Chicken,Schezwan Chicken Meatball,Chick...",1,https://api.pizzahut.io/v1/content/en-in/in-1/...,"[{'mediumPan': [{'price': 7}], 'mediumstuffedc..."
6,6,Chicken Tikka Supreme,False,6,"Chicken Tikka,Chicken Malai Tikka,Onion,Red Pa...",1,https://api.pizzahut.io/v1/content/en-in/in-1/...,"[{'mediumPan': [{'price': 7}], 'mediumstuffedc..."
7,7,Triple Chicken Feast,False,8,"Schezwan Chicken Meatball Herbed Chicken,Chick...",1,https://api.pizzahut.io/v1/content/en-in/in-1/...,"[{'mediumPan': [{'price': 8}], 'mediumstuffedc..."
8,8,Chicken Tikka,False,7,"Chicken Tikka, Onion, Tomato",1,https://api.pizzahut.io/v1/content/en-in/in-1/...,"[{'mediumPan': [{'price': 7}], 'mediumstuffedc..."
9,9,Double Chicken Sausage,False,5,Chicken Sausage,1,https://api.pizzahut.io/v1/content/en-in/in-1/...,"[{'mediumPan': [{'price': 5}], 'mediumstuffedc..."
10,10,Spiced Chicken Meatballs,False,4,Schezwan Chicken Meatball Onion,1,https://api.pizzahut.io/v1/content/en-in/in-1/...,"[{'mediumPan': [{'price': 4}], 'mediumstuffedc..."
11,11,Double Cheese,True,3,Extra Cheese on Cheese,1,https://api.pizzahut.io/v1/content/en-in/in-1/...,"[{'mediumPan': [{'price': 3}], 'mediumstuffedc..."
12,12,Chicken Pepper Crunch,False,5,"Herbed Chicken, Onion, Green Capsicum, Red Cap...",1,https://api.pizzahut.io/v1/content/en-in/in-1/...,"[{'mediumPan': [{'price': 5}], 'mediumstuffedc..."
13,13,Italian Chicken Feast,False,6,"Herbed Chicken, Onion, Green Capsicum, Red Cap...",1,https://api.pizzahut.io/v1/content/en-in/in-1/...,"[{'mediumPan': [{'price': 6}], 'mediumstuffedc..."
14,14,Corn & Cheese,True,5,"Cheese ,Sweet Corn",1,https://api.pizzahut.io/v1/content/en-in/in-1/...,"[{'mediumPan': [{'price': 5}], 'mediumstuffedc..."
15,15,Tandoori Onion,True,6,Cheese & Onion in Tandoori sause,1,https://api.pizzahut.io/v1/content/en-in/in-1/...,"[{'mediumPan': [{'price': 7}], 'mediumstuffedc..."
16,16,Chicken Pepperoni,False,5,"Cheese ,Chicken pepperoni",1,https://api.pizzahut.io/v1/content/en-in/in-1/...,"[{'mediumPan': [{'price': 6}], 'mediumstuffedc..."
17,17,Chicken N Corn Delight,False,9,"Cheese ,Chicken pepperoni",1,https://api.pizzahut.io/v1/content/en-in/in-1/...,"[{'mediumPan': [{'price': 9}], 'mediumstuffedc..."
18,18,Farmers Pick,True,29,"Onion Herbed & Green Capsicum, Red Capsicum, M...",1,https://api.pizzahut.io/v1/content/en-in/in-1/...,"[{'mediumPan': [{'price': 5}], 'mediumstuffedc..."
19,19,Classic Corn,True,5,"Pizza topped with our Classic Pan sauce, sweet...",1,https://api.pizzahut.io/v1/content/en-in/in-1/...,"[{'mediumPan': [{'price': 5}], 'mediumstuffedc..."
20,20,Classic Onion Capsicum,True,4,"Pizza topped with our Classic Pan sauce, crunc...",1,https://api.pizzahut.io/v1/content/en-in/in-1/...,"[{'mediumPan': [{'price': 4}], 'mediumstuffedc..."
21,21,Italian Onion Tomato,True,8,Pizza topped with our Chef's Special Italian s...,1,https://api.pizzahut.io/v1/content/en-in/in-1/...,"[{'mediumPan': [{'price': 8}], 'mediumstuffedc..."
22,22,Tandoori Mushroom & Sweet Corn,True,5,Pizza topped with our signature tandoori sauce...,1,https://api.pizzahut.io/v1/content/en-in/in-1/...,"[{'mediumPan': [{'price': 5}], 'mediumstuffedc..."
23,23,Schezwan Corn & Capsicum,True,6,"Pizza topped with Spicy Schezwan sauce, sweet ...",1,https://api.pizzahut.io/v1/content/en-in/in-1/...,"[{'mediumPan': [{'price': 6}], 'mediumstuffedc..."
24,24,Only Cheesy,True,40,Pizza topped with cheesy dressing and mozzarel...,1,https://api.pizzahut.io/v1/content/en-in/in-1/...,"[{'mediumPan': [{'price': 40}], 'mediumstuffed..."
25,25,Classic Sausage,False,8,"Pizza topped with our Classic Pan sauce, flavo...",1,https://api.pizzahut.io/v1/content/en-in/in-1/...,"[{'mediumPan': [{'price': 8}], 'mediumstuffedc..."
26,26,Classic Paneer Capsicum & Onion,True,6,"Pizza topped with our Classic Pan sauce, flavo...",1,https://api.pizzahut.io/v1/content/en-in/in-1/...,"[{'mediumPan': [{'price': 6}], 'mediumstuffedc..."
27,27,Italian Pepperoni & Onion,False,5,Pizza topped with our Chef's Special Italian s...,1,https://api.pizzahut.io/v1/content/en-in/in-1/...,"[{'mediumPan': [{'price': 5}], 'mediumstuffedc..."
28,28,Schezwan Meatball & Capsicum,False,10,"Pizza topped with Spicy Schezwan sauce, crunch...",1,https://api.pizzahut.io/v1/content/en-in/in-1/...,"[{'mediumPan': [{'price': 12}], 'mediumstuffed..."
29,29,Tandoori Tikka & Onion,False,5,Pizza topped with our signature tandoori sauce...,1,https://api.pizzahut.io/v1/content/en-in/in-1/...,"[{'mediumPan': [{'price': 6}], 'mediumstuffedc..."
30,30,Classic Loaded Chicken Delight,False,9,"Pizza topped with our Classic Pan sauce, herbe...",1,https://api.pizzahut.io/v1/content/en-in/in-1/...,"[{'mediumPan': [{'price': 9}], 'mediumstuffedc..."

In [9]:
print(response.status_code)
print(response.json())

200
{'id': 1, 'name': 'Margherita', 'veg': True, 'price': 3, 'description': 'Cheese', 'quantity': 1, 'img': 'https://api.pizzahut.io/v1/content/en-in/in-1/images/pizza/margherita.90f9451fd66871fb6f9cf7d506053f18.1.jpg?width=550', 'sizeandcrust': [{'mediumPan': [{'price': 3}], 'mediumstuffedcrustcheesemax': [{'price': 5}], 'mediumstuffedcrustvegkebab': [{'price': 8}]}]}

In [12]:
df.to_csv("pizza_dataset.csv",index=False)

In [13]:
df

,id,name,veg,price,description,quantity,img,sizeandcrust
0,1,Margherita,True,3,Cheese,1,https://api.pizzahut.io/v1/content/en-in/in-1/...,"[{'mediumPan': [{'price': 3}], 'mediumstuffedc..."
1,2,Tandoori Paneer,True,7,"Spiced paneeer, Onion,Green Capsicum & Red Pap...",1,https://api.pizzahut.io/v1/content/en-in/in-1/...,"[{'mediumPan': [{'price': 7}], 'mediumstuffedc..."
2,3,Veggie Supreme,True,8,"Black Olives,Green Capsicum, Mushroom, Onion,R...",1,https://api.pizzahut.io/v1/content/en-in/in-1/...,"[{'mediumPan': [{'price': 8}], 'mediumstuffedc..."
3,4,Double Paneer Supreme,True,6,"Spiced Paneer, Herbed Onion&Green Capsicum, Re...",1,https://api.pizzahut.io/v1/content/en-in/in-1/...,"[{'mediumPan': [{'price': 6}], 'mediumstuffedc..."
4,4,Veggie Kebab Surprise,True,4,"Veg Kebab,Onion,Green Capsicum,Tomato & Sweet ...",1,https://api.pizzahut.io/v1/content/en-in/in-1/...,"[{'mediumPan': [{'price': 5}], 'mediumstuffedc..."
5,5,Chicken Supreme,False,7,"Herbed Chicken,Schezwan Chicken Meatball,Chick...",1,https://api.pizzahut.io/v1/content/en-in/in-1/...,"[{'mediumPan': [{'price': 7}], 'mediumstuffedc..."
6,6,Chicken Tikka Supreme,False,6,"Chicken Tikka,Chicken Malai Tikka,Onion,Red Pa...",1,https://api.pizzahut.io/v1/content/en-in/in-1/...,"[{'mediumPan': [{'price': 7}], 'mediumstuffedc..."
7,7,Triple Chicken Feast,False,8,"Schezwan Chicken Meatball Herbed Chicken,Chick...",1,https://api.pizzahut.io/v1/content/en-in/in-1/...,"[{'mediumPan': [{'price': 8}], 'mediumstuffedc..."
8,8,Chicken Tikka,False,7,"Chicken Tikka, Onion, Tomato",1,https://api.pizzahut.io/v1/content/en-in/in-1/...,"[{'mediumPan': [{'price': 7}], 'mediumstuffedc..."
9,9,Double Chicken Sausage,False,5,Chicken Sausage,1,https://api.pizzahut.io/v1/content/en-in/in-1/...,"[{'mediumPan': [{'price': 5}], 'mediumstuffedc..."
10,10,Spiced Chicken Meatballs,False,4,Schezwan Chicken Meatball Onion,1,https://api.pizzahut.io/v1/content/en-in/in-1/...,"[{'mediumPan': [{'price': 4}], 'mediumstuffedc..."
11,11,Double Cheese,True,3,Extra Cheese on Cheese,1,https://api.pizzahut.io/v1/content/en-in/in-1/...,"[{'mediumPan': [{'price': 3}], 'mediumstuffedc..."
12,12,Chicken Pepper Crunch,False,5,"Herbed Chicken, Onion, Green Capsicum, Red Cap...",1,https://api.pizzahut.io/v1/content/en-in/in-1/...,"[{'mediumPan': [{'price': 5}], 'mediumstuffedc..."
13,13,Italian Chicken Feast,False,6,"Herbed Chicken, Onion, Green Capsicum, Red Cap...",1,https://api.pizzahut.io/v1/content/en-in/in-1/...,"[{'mediumPan': [{'price': 6}], 'mediumstuffedc..."
14,14,Corn & Cheese,True,5,"Cheese ,Sweet Corn",1,https://api.pizzahut.io/v1/content/en-in/in-1/...,"[{'mediumPan': [{'price': 5}], 'mediumstuffedc..."
15,15,Tandoori Onion,True,6,Cheese & Onion in Tandoori sause,1,https://api.pizzahut.io/v1/content/en-in/in-1/...,"[{'mediumPan': [{'price': 7}], 'mediumstuffedc..."
16,16,Chicken Pepperoni,False,5,"Cheese ,Chicken pepperoni",1,https://api.pizzahut.io/v1/content/en-in/in-1/...,"[{'mediumPan': [{'price': 6}], 'mediumstuffedc..."
17,17,Chicken N Corn Delight,False,9,"Cheese ,Chicken pepperoni",1,https://api.pizzahut.io/v1/content/en-in/in-1/...,"[{'mediumPan': [{'price': 9}], 'mediumstuffedc..."
18,18,Farmers Pick,True,29,"Onion Herbed & Green Capsicum, Red Capsicum, M...",1,https://api.pizzahut.io/v1/content/en-in/in-1/...,"[{'mediumPan': [{'price': 5}], 'mediumstuffedc..."
19,19,Classic Corn,True,5,"Pizza topped with our Classic Pan sauce, sweet...",1,https://api.pizzahut.io/v1/content/en-in/in-1/...,"[{'mediumPan': [{'price': 5}], 'mediumstuffedc..."
20,20,Classic Onion Capsicum,True,4,"Pizza topped with our Classic Pan sauce, crunc...",1,https://api.pizzahut.io/v1/content/en-in/in-1/...,"[{'mediumPan': [{'price': 4}], 'mediumstuffedc..."
21,21,Italian Onion Tomato,True,8,Pizza topped with our Chef's Special Italian s...,1,https://api.pizzahut.io/v1/content/en-in/in-1/...,"[{'mediumPan': [{'price': 8}], 'mediumstuffedc..."
22,22,Tandoori Mushroom & Sweet Corn,True,5,Pizza topped with our signature tandoori sauce...,1,https://api.pizzahut.io/v1/content/en-in/in-1/...,"[{'mediumPan': [{'price': 5}], 'mediumstuffedc..."
23,23,Schezwan Corn & Capsicum,True,6,"Pizza topped with Spicy Schezwan sauce, sweet ...",1,https://api.pizzahut.io/v1/content/en-in/in-1/...,"[{'mediumPan': [{'price': 6}], 'mediumstuffedc..."
24,24,Only Cheesy,True,40,Pizza topped with cheesy dressing and mozzarel...,1,https://api.pizzahut.io/v1/content/en-in/in-1/...,"[{'mediumPan': [{'price': 40}], 'mediumstuffed..."
25,25,Classic Sausage,False,8,"Pizza topped with our Classic Pan sauce, flavo...",1,https://api.pizzahut.io/v1/content/en-in/in-1/...,"[{'mediumPan': [{'price': 8}], 'mediumstuffedc..."
26,26,Classic Paneer Capsicum & Onion,True,6,"Pizza topped with our Classic Pan sauce, flavo...",1,https://api.pizzahut.io/v1/content/en-in/in-1/...,"[{'mediumPan': [{'price': 6}], 'mediumstuffedc..."
27,27,Italian Pepperoni & Onion,False,5,Pizza topped with our Chef's Special Italian s...,1,https://api.pizzahut.io/v1/content/en-in/in-1/...,"[{'mediumPan': [{'price': 5}], 'mediumstuffedc..."
28,28,Schezwan Meatball & Capsicum,False,10,"Pizza topped with Spicy Schezwan sauce, crunch...",1,https://api.pizzahut.io/v1/content/en-in/in-1/...,"[{'mediumPan': [{'price': 12}], 'mediumstuffed..."
29,29,Tandoori Tikka & Onion,False,5,Pizza topped with our signature tandoori sauce...,1,https://api.pizzahut.io/v1/content/en-in/in-1/...,"[{'mediumPan': [{'price': 6}], 'mediumstuffedc..."
30,30,Classic Loaded Chicken Delight,False,9,"Pizza topped with our Classic Pan sauce, herbe...",1,https://api.pizzahut.io/v1/content/en-in/in-1/...,"[{'mediumPan': [{'price': 9}], 'mediumstuffedc..."

In [14]:
import os
print(os.getcwd())

C:\Users\DELL