In [1]:
import numpy as np
import pandas as pd

In [5]:
date=pd.read_csv(r'C:\Users\DELL\Downloads\restaurant_orders.csv')
time=pd.read_csv(r"C:\Users\DELL\Downloads\messages.csv.zip")

In [6]:
date.head()

,Order ID,Customer Name,Food Item,Category,Quantity,Price,Payment Method,Order Time
0,2268,Mary Vega DDS,Pasta,Main,5,16.52,Cash,2025-02-02 14:28:41
1,3082,Brandon Myers,Brownie,Dessert,4,17.27,Debit Card,2025-06-08 10:57:47
2,3160,Margaret Wells,Pasta,Main,1,3.37,Credit Card,2025-03-04 07:41:41
3,1272,Michael Matthews,Pasta,Main,5,2.20,Online Payment,2025-05-15 12:43:45
4,9447,Connor Williams,Soup,Starter,1,12.23,Cash,2025-03-15 14:25:56

In [7]:
time.head()

                  date                                                msg
0  2012-01-02 00:21:00                            нужен парень 0965188229
1  2012-01-02 00:24:00                       Всем привет! Как настроение?
2  2012-01-02 00:27:00  ИЩЮ ВТОРУЮ ПОЛОВИНКУ МНЕ 23 ЗОВУТ ВАНЯ ПИШИТЕ ...
3  2012-01-02 00:27:00     Эля  встречала в шумной компании! Все отлично!
4  2012-01-02 00:27:00  Парень катается по городу. Нужна девушка. 0992...

In [8]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Order ID        500 non-null    int64
 1   Customer Name   500 non-null    object
 2   Food Item       500 non-null    object
 3   Category        500 non-null    object
 4   Quantity        500 non-null    int64
 5   Price           500 non-null    float64
 6   Payment Method  500 non-null    object
 7   Order Time      500 non-null    object
dtypes: float64(1), int64(2), object(5)
memory usage: 31.4+ KB

time.info()

In [10]:
# Converting to datetime datatype
date['date'] = pd.to_datetime(date['Order Time']) #we converted order time to date

In [11]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Order ID        500 non-null    int64
 1   Customer Name   500 non-null    object
 2   Food Item       500 non-null    object
 3   Category        500 non-null    object
 4   Quantity        500 non-null    int64
 5   Price           500 non-null    float64
 6   Payment Method  500 non-null    object
 7   Order Time      500 non-null    object
 8   date            500 non-null    datetime64[ns]
dtypes: datetime64[ns](1), float64(1), int64(2), object(5)
memory usage: 35.3+ KB

In [27]:
# date.drop(columns=['Order ID','Customer Name','Food Item',"Quantity",'Price','Payment Method'],inplace=True)

In [28]:
date['date_year']=date['date'].dt.year
date.sample(5)

,Category,Order Time,date,date_year,date_month_no,date_day,date_dow,date_dow_name
470,Main,2025-08-10 02:16:39,2025-08-10 02:16:39,2025,8,10,6,Sunday
140,Starter,2025-05-21 21:54:55,2025-05-21 21:54:55,2025,5,21,2,Wednesday
10,Main,2025-04-28 08:09:19,2025-04-28 08:09:19,2025,4,28,0,Monday
464,Starter,2025-06-27 00:46:31,2025-06-27 00:46:31,2025,6,27,4,Friday
358,Starter,2025-06-07 09:10:16,2025-06-07 09:10:16,2025,6,7,5,Saturday

In [36]:
date['date_month_no'] = date['date'].dt.month_name()

date.head()

,Category,Order Time,date,date_year,date_month_no,date_day,date_dow,date_dow_name
0,Main,2025-02-02 14:28:41,2025-02-02 14:28:41,2025,February,2,6,Sunday
1,Dessert,2025-06-08 10:57:47,2025-06-08 10:57:47,2025,June,8,6,Sunday
2,Main,2025-03-04 07:41:41,2025-03-04 07:41:41,2025,March,4,1,Tuesday
3,Main,2025-05-15 12:43:45,2025-05-15 12:43:45,2025,May,15,3,Thursday
4,Starter,2025-03-15 14:25:56,2025-03-15 14:25:56,2025,March,15,5,Saturday

In [30]:
date['date_month_no'] = date['date'].dt.month

date.head()

,Category,Order Time,date,date_year,date_month_no,date_day,date_dow,date_dow_name
0,Main,2025-02-02 14:28:41,2025-02-02 14:28:41,2025,2,2,6,Sunday
1,Dessert,2025-06-08 10:57:47,2025-06-08 10:57:47,2025,6,8,6,Sunday
2,Main,2025-03-04 07:41:41,2025-03-04 07:41:41,2025,3,4,1,Tuesday
3,Main,2025-05-15 12:43:45,2025-05-15 12:43:45,2025,5,15,3,Thursday
4,Starter,2025-03-15 14:25:56,2025-03-15 14:25:56,2025,3,15,5,Saturday

In [31]:
date['date_day'] = date['date'].dt.day

date.head()

,Category,Order Time,date,date_year,date_month_no,date_day,date_dow,date_dow_name
0,Main,2025-02-02 14:28:41,2025-02-02 14:28:41,2025,2,2,6,Sunday
1,Dessert,2025-06-08 10:57:47,2025-06-08 10:57:47,2025,6,8,6,Sunday
2,Main,2025-03-04 07:41:41,2025-03-04 07:41:41,2025,3,4,1,Tuesday
3,Main,2025-05-15 12:43:45,2025-05-15 12:43:45,2025,5,15,3,Thursday
4,Starter,2025-03-15 14:25:56,2025-03-15 14:25:56,2025,3,15,5,Saturday

In [32]:
# day of week
date['date_dow'] = date['date'].dt.dayofweek

date.head()

,Category,Order Time,date,date_year,date_month_no,date_day,date_dow,date_dow_name
0,Main,2025-02-02 14:28:41,2025-02-02 14:28:41,2025,2,2,6,Sunday
1,Dessert,2025-06-08 10:57:47,2025-06-08 10:57:47,2025,6,8,6,Sunday
2,Main,2025-03-04 07:41:41,2025-03-04 07:41:41,2025,3,4,1,Tuesday
3,Main,2025-05-15 12:43:45,2025-05-15 12:43:45,2025,5,15,3,Thursday
4,Starter,2025-03-15 14:25:56,2025-03-15 14:25:56,2025,3,15,5,Saturday

In [35]:
# day of week - name

date['date_dow_name'] = date['date'].dt.day_name()

date.head()

,Category,Order Time,date,date_year,date_month_no,date_day,date_dow,date_dow_name
0,Main,2025-02-02 14:28:41,2025-02-02 14:28:41,2025,2,2,6,Sunday
1,Dessert,2025-06-08 10:57:47,2025-06-08 10:57:47,2025,6,8,6,Sunday
2,Main,2025-03-04 07:41:41,2025-03-04 07:41:41,2025,3,4,1,Tuesday
3,Main,2025-05-15 12:43:45,2025-05-15 12:43:45,2025,5,15,3,Thursday
4,Starter,2025-03-15 14:25:56,2025-03-15 14:25:56,2025,3,15,5,Saturday

In [39]:
date['date_is_weekend'] = np.where(date['date_dow_name'].isin(['Sunday', 'Saturday']), 1,0)
date.head()

,Category,Order Time,date,date_year,date_month_no,date_day,date_dow,date_dow_name,date_is_weekend
0,Main,2025-02-02 14:28:41,2025-02-02 14:28:41,2025,February,2,6,Sunday,1
1,Dessert,2025-06-08 10:57:47,2025-06-08 10:57:47,2025,June,8,6,Sunday,1
2,Main,2025-03-04 07:41:41,2025-03-04 07:41:41,2025,March,4,1,Tuesday,0
3,Main,2025-05-15 12:43:45,2025-05-15 12:43:45,2025,May,15,3,Thursday,0
4,Starter,2025-03-15 14:25:56,2025-03-15 14:25:56,2025,March,15,5,Saturday,1

In [45]:
date['date_week'] = date['date'].dt.isocalendar().week.astype(int)

date.head()

,Category,Order Time,date,date_year,date_month_no,date_day,date_dow,date_dow_name,date_is_weekend,date_week
0,Main,2025-02-02 14:28:41,2025-02-02 14:28:41,2025,February,2,6,Sunday,1,5
1,Dessert,2025-06-08 10:57:47,2025-06-08 10:57:47,2025,June,8,6,Sunday,1,23
2,Main,2025-03-04 07:41:41,2025-03-04 07:41:41,2025,March,4,1,Tuesday,0,10
3,Main,2025-05-15 12:43:45,2025-05-15 12:43:45,2025,May,15,3,Thursday,0,20
4,Starter,2025-03-15 14:25:56,2025-03-15 14:25:56,2025,March,15,5,Saturday,1,11

In [47]:
date['quarter'] = date['date'].dt.quarter
date.head()

,Category,Order Time,date,date_year,date_month_no,date_day,date_dow,date_dow_name,date_is_weekend,date_week,quarter
0,Main,2025-02-02 14:28:41,2025-02-02 14:28:41,2025,February,2,6,Sunday,1,5,1
1,Dessert,2025-06-08 10:57:47,2025-06-08 10:57:47,2025,June,8,6,Sunday,1,23,2
2,Main,2025-03-04 07:41:41,2025-03-04 07:41:41,2025,March,4,1,Tuesday,0,10,1
3,Main,2025-05-15 12:43:45,2025-05-15 12:43:45,2025,May,15,3,Thursday,0,20,2
4,Starter,2025-03-15 14:25:56,2025-03-15 14:25:56,2025,March,15,5,Saturday,1,11,1

In [51]:
date['semester'] = np.where(date['quarter'].isin([1,2]), 1, 2)

date.sample(6)

,Category,Order Time,date,date_year,date_month_no,date_day,date_dow,date_dow_name,date_is_weekend,date_week,quarter,semester
461,Dessert,2025-04-24 09:40:02,2025-04-24 09:40:02,2025,April,24,3,Thursday,0,17,2,1
44,Starter,2025-05-15 13:59:45,2025-05-15 13:59:45,2025,May,15,3,Thursday,0,20,2,1
400,Main,2025-07-30 11:33:27,2025-07-30 11:33:27,2025,July,30,2,Wednesday,0,31,3,2
258,Starter,2025-01-18 18:55:13,2025-01-18 18:55:13,2025,January,18,5,Saturday,1,3,1,1
97,Starter,2025-06-21 19:24:43,2025-06-21 19:24:43,2025,June,21,5,Saturday,1,25,2,1
374,Starter,2025-06-06 22:35:12,2025-06-06 22:35:12,2025,June,6,4,Friday,0,23,2,1

In [52]:
#Extract Time elapsed between dates
import datetime

today = datetime.datetime.today()

today

datetime.datetime(2026, 8, 1, 2, 49, 33, 647959)

In [53]:
today - date['date']

0     544 days 12:20:52.647959
1     418 days 15:51:46.647959
2     514 days 19:07:52.647959
3     442 days 14:05:48.647959
4     503 days 12:23:37.647959
                ...
495   562 days 07:28:31.647959
496   381 days 11:49:14.647959
497   362 days 03:02:05.647959
498   373 days 18:39:27.647959
499   356 days 21:38:06.647959
Name: date, Length: 500, dtype: timedelta64[ns]

In [54]:
(today - date['date']).dt.days

0      544
1      418
2      514
3      442
4      503
      ...
495    562
496    381
497    362
498    373
499    356
Name: date, Length: 500, dtype: int64

In [58]:
# Months passed

np.round((today -date['date']) / np.timedelta64(1, 'D')/30.44,0)

0      18.0
1      14.0
2      17.0
3      15.0
4      17.0
       ...
495    18.0
496    13.0
497    12.0
498    12.0
499    12.0
Name: date, Length: 500, dtype: float64

In [59]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1147100 entries, 0 to 1147099
Data columns (total 2 columns):
 #   Column  Non-Null Count    Dtype
---  ------  --------------    -----
 0   date    1147100 non-null  object
 1   msg     1147100 non-null  object
dtypes: object(2)
memory usage: 17.5+ MB

In [60]:
# Converting to datetime datatype
time['date'] = pd.to_datetime(time['date'])

In [61]:
time['hour'] = time['date'].dt.hour
time['min'] = time['date'].dt.minute
time['sec'] = time['date'].dt.second

time.head()

,date,msg,hour,min,sec
0,2012-01-02 00:21:00,нужен парень 0965188229,0,21,0
1,2012-01-02 00:24:00,Всем привет! Как настроение?,0,24,0
2,2012-01-02 00:27:00,ИЩЮ ВТОРУЮ ПОЛОВИНКУ МНЕ 23 ЗОВУТ ВАНЯ ПИШИТЕ ...,0,27,0
3,2012-01-02 00:27:00,Эля встречала в шумной компании! Все отлично!,0,27,0
4,2012-01-02 00:27:00,Парень катается по городу. Нужна девушка. 0992...,0,27,0

In [62]:
time['time'] = time['date'].dt.time

time.head()

,date,msg,hour,min,sec,time
0,2012-01-02 00:21:00,нужен парень 0965188229,0,21,0,00:21:00
1,2012-01-02 00:24:00,Всем привет! Как настроение?,0,24,0,00:24:00
2,2012-01-02 00:27:00,ИЩЮ ВТОРУЮ ПОЛОВИНКУ МНЕ 23 ЗОВУТ ВАНЯ ПИШИТЕ ...,0,27,0,00:27:00
3,2012-01-02 00:27:00,Эля встречала в шумной компании! Все отлично!,0,27,0,00:27:00
4,2012-01-02 00:27:00,Парень катается по городу. Нужна девушка. 0992...,0,27,0,00:27:00

In [63]:
today - time['date']

0         5325 days 02:28:33.647959
1         5325 days 02:25:33.647959
2         5325 days 02:22:33.647959
3         5325 days 02:22:33.647959
4         5325 days 02:22:33.647959
                     ...
1147095   3468 days 02:27:33.647959
1147096   3468 days 02:27:33.647959
1147097   3468 days 02:27:33.647959
1147098   3468 days 02:25:33.647959
1147099   3468 days 02:23:33.647959
Name: date, Length: 1147100, dtype: timedelta64[ns]

In [64]:
# in seconds

(today - time['date'])/np.timedelta64(1,'s')

0          4.600889e+08
1          4.600887e+08
2          4.600886e+08
3          4.600886e+08
4          4.600886e+08
               ...
1147095    2.996441e+08
1147096    2.996441e+08
1147097    2.996441e+08
1147098    2.996439e+08
1147099    2.996438e+08
Name: date, Length: 1147100, dtype: float64

In [65]:
# in minutes

(today - time['date'])/np.timedelta64(1,'m')

0          7.668149e+06
1          7.668146e+06
2          7.668143e+06
3          7.668143e+06
4          7.668143e+06
               ...
1147095    4.994068e+06
1147096    4.994068e+06
1147097    4.994068e+06
1147098    4.994066e+06
1147099    4.994064e+06
Name: date, Length: 1147100, dtype: float64

In [66]:
# in hours

(today - time['date'])/np.timedelta64(1,'h')

0          127802.476013
1          127802.426013
2          127802.376013
3          127802.376013
4          127802.376013
               ...
1147095     83234.459347
1147096     83234.459347
1147097     83234.459347
1147098     83234.426013
1147099     83234.392680
Name: date, Length: 1147100, dtype: float64