In [66]:
import pandas as pd
import numpy as np

In [67]:
from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import MinMaxScaler
from sklearn.pipeline import Pipeline,make_pipeline
from sklearn.feature_selection import SelectKBest,chi2
from sklearn.tree import DecisionTreeClassifier

In [68]:
df=pd.read_csv(r"C:\Users\DELL\Downloads\tested.csv")

In [69]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,0,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,0,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,0,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,1,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S

In [70]:
df.drop(columns=['PassengerId','Name','Ticket','Cabin'],inplace=True)

In [71]:
df.head()

   Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0         0       3    male  34.5      0      0   7.8292        Q
1         1       3  female  47.0      1      0   7.0000        S
2         0       2    male  62.0      0      0   9.6875        Q
3         0       3    male  27.0      0      0   8.6625        S
4         1       3  female  22.0      1      1  12.2875        S

In [72]:
# Step 1 -> train/test/split
X_train,X_test,y_train,y_test = train_test_split(df.drop(columns=['Survived']),
                                                 df['Survived'],
                                                 test_size=0.2,
                                                random_state=42)

In [74]:
X_train.head(2)

     Pclass   Sex   Age  SibSp  Parch  Fare Embarked
336       2  male  32.0      0      0  13.0        S
31        2  male  24.0      2      0  31.5        S

In [76]:
y_train.head(2)

336    0
31     0
Name: Survived, dtype: int64

In [78]:
df.isnull().sum()

Survived     0
Pclass       0
Sex          0
Age         86
SibSp        0
Parch        0
Fare         1
Embarked     0
dtype: int64

In [79]:
# Applying imputation

si_age = SimpleImputer()
si_fare = SimpleImputer(strategy='most_frequent')

X_train_age = si_age.fit_transform(X_train[['Age']])
X_train_fare = si_fare.fit_transform(X_train[['Fare']])

X_test_age = si_age.transform(X_test[['Age']])
X_test_fare = si_fare.transform(X_test[['Fare']])

In [81]:
X_train_age

array([[32.        ],
       [24.        ],
       [30.11576336],
       [24.        ],
       [19.        ],
       [30.11576336],
       [25.        ],
       [ 6.        ],
       [46.        ],
       [14.        ],
       [25.        ],
       [10.        ],
       [31.        ],
       [17.        ],
       [30.11576336],
       [35.        ],
       [24.        ],
       [30.11576336],
       [23.        ],
       [27.        ],
       [27.        ],
       [30.11576336],
       [17.        ],
       [23.        ],
       [30.11576336],
       [22.        ],
       [30.11576336],
       [61.        ],
       [11.5       ],
       [30.11576336],
       [ 6.        ],
       [30.11576336],
       [22.        ],
       [26.        ],
       [ 0.92      ],
       [22.        ],
       [30.11576336],
       [27.        ],
       [18.        ],
       [30.11576336],
       [33.        ],
       [23.        ],
       [36.        ],
       [30.11576336],
       [63.        ],
       [22.        ],
       [53.        ],
       [23.        ],
       [60.5       ],
       [31.        ],
       [31.        ],
       [26.        ],
       [30.        ],
       [30.11576336],
       [18.5       ],
       [20.        ],
       [30.11576336],
       [50.        ],
       [23.        ],
       [30.11576336],
       [30.11576336],
       [31.        ],
       [35.        ],
       [33.        ],
       [29.        ],
       [36.        ],
       [37.        ],
       [30.11576336],
       [48.        ],
       [59.        ],
       [54.        ],
       [33.        ],
       [30.11576336],
       [40.        ],
       [ 0.83      ],
       [23.        ],
       [30.11576336],
       [30.        ],
       [36.        ],
       [30.11576336],
       [ 8.        ],
       [ 8.        ],
       [30.        ],
       [30.11576336],
       [30.11576336],
       [42.        ],
       [23.        ],
       [30.11576336],
       [20.        ],
       [26.        ],
       [67.        ],
       [36.        ],
       [29.        ],
       [18.        ],
       [13.        ],
       [21.        ],
       [18.        ],
       [21.        ],
       [27.        ],
       [ 2.        ],
       [18.        ],
       [30.11576336],
       [29.        ],
       [22.        ],
       [30.11576336],
       [27.        ],
       [60.        ],
       [30.11576336],
       [28.        ],
       [76.        ],
       [28.        ],
       [45.        ],
       [29.        ],
       [22.        ],
       [31.        ],
       [21.        ],
       [21.        ],
       [42.        ],
       [35.        ],
       [21.        ],
       [47.        ],
       [18.        ],
       [47.        ],
       [25.        ],
       [24.        ],
       [48.        ],
       [30.11576336],
       [19.        ],
       [50.        ],
       [17.        ],
       [30.11576336],
       [26.        ],
       [27.        ],
       [18.        ],
       [40.5       ],
       [49.        ],
       [42.        ],
       [45.        ],
       [27.        ],
       [30.11576336],
       [29.        ],
       [30.        ],
       [39.        ],
       [30.11576336],
       [24.        ],
       [25.        ],
       [46.        ],
       [ 2.        ],
       [40.        ],
       [30.11576336],
       [36.        ],
       [64.        ],
       [ 1.        ],
       [64.        ],
       [ 9.        ],
       [30.11576336],
       [ 1.        ],
       [18.        ],
       [30.        ],
       [22.        ],
       [43.        ],
       [30.11576336],
       [ 5.        ],
       [45.        ],
       [41.        ],
       [31.        ],
       [26.5       ],
       [13.        ],
       [30.11576336],
       [18.        ],
       [30.11576336],
       [62.        ],
       [21.        ],
       [18.        ],
       [12.        ],
       [53.        ],
       [25.        ],
       [ 0.75      ],
       [30.11576336],
       [26.        ],
       [30.11576336],
       [30.11576336],
       [30.11576336],
       [44.        ],
       [45.        ],
       [30.11576336],
       [30.11576336],
       [30.11576336],
       [45.        ],
       [21.        ],
       [26.        ],
       [23.        ],
       [18.5       ],
       [41.        ],
       [30.11576336],
       [61.        ],
       [27.        ],
       [30.11576336],
       [21.        ],
       [25.        ],
       [27.        ],
       [55.        ],
       [55.        ],
       [26.        ],
       [36.        ],
       [30.11576336],
       [12.        ],
       [35.        ],
       [30.11576336],
       [32.5       ],
       [38.        ],
       [22.        ],
       [30.11576336],
       [54.        ],
       [43.        ],
       [23.        ],
       [30.11576336],
       [60.        ],
       [27.        ],
       [20.        ],
       [30.11576336],
       [42.        ],
       [32.        ],
       [30.11576336],
       [33.        ],
       [30.11576336],
       [30.11576336],
       [20.        ],
       [22.5       ],
       [21.        ],
       [14.        ],
       [36.5       ],
       [30.11576336],
       [26.        ],
       [50.        ],
       [23.        ],
       [18.        ],
       [24.        ],
       [42.        ],
       [18.        ],
       [13.        ],
       [32.        ],
       [47.        ],
       [29.        ],
       [39.        ],
       [19.        ],
       [14.5       ],
       [30.11576336],
       [22.        ],
       [24.        ],
       [64.        ],
       [24.        ],
       [17.        ],
       [26.        ],
       [26.        ],
       [20.        ],
       [30.11576336],
       [30.11576336],
       [24.        ],
       [17.        ],
       [ 0.33      ],
       [ 7.        ],
       [30.        ],
       [57.        ],
       [34.        ],
       [45.        ],
       [21.        ],
       [28.        ],
       [28.        ],
       [47.        ],
       [36.        ],
       [ 6.        ],
       [30.11576336],
       [30.        ],
       [ 1.        ],
       [30.11576336],
       [30.11576336],
       [20.        ],
       [16.        ],
       [30.        ],
       [45.        ],
       [63.        ],
       [17.        ],
       [30.11576336],
       [30.11576336],
       [48.        ],
       [29.        ],
       [37.        ],
       [43.        ],
       [30.        ],
       [38.        ],
       [22.        ],
       [30.11576336],
       [30.11576336],
       [27.        ],
       [24.        ],
       [40.        ],
       [40.        ],
       [38.5       ],
       [17.        ],
       [22.        ],
       [30.11576336],
       [60.        ],
       [30.11576336],
       [20.        ],
       [27.        ],
       [ 9.        ],
       [37.        ],
       [30.11576336],
       [28.        ],
       [30.11576336],
       [24.        ],
       [53.        ],
       [58.        ],
       [28.        ],
       [55.        ],
       [30.        ],
       [32.        ],
       [30.11576336],
       [30.        ],
       [33.        ],
       [49.        ],
       [18.        ],
       [48.        ],
       [38.        ],
       [30.11576336],
       [30.11576336],
       [55.        ],
       [30.11576336],
       [21.        ],
       [21.        ],
       [46.        ],
       [24.        ],
       [30.11576336]])

In [84]:
# one hot encoding Sex and Embarked

ohe_sex = OneHotEncoder(sparse_output=False,handle_unknown='ignore')
ohe_embarked = OneHotEncoder(sparse_output=False,handle_unknown='ignore')

X_train_sex = ohe_sex.fit_transform(X_train[['Sex']])
X_train_embarked = ohe_embarked.fit_transform(X_train[['Embarked']])

X_test_sex = ohe_sex.transform(X_test[['Sex']])
X_test_embarked = ohe_embarked.transform(X_test[['Embarked']])

In [85]:
X_train_embarked

array([[0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       ...,
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.]], shape=(334, 3))

In [86]:
X_train_sex

array([[0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.]])

In [87]:
X_train_rem = X_train.drop(columns=['Sex','Age','Embarked'])

In [88]:
X_test_rem = X_test.drop(columns=['Sex','Age','Embarked'])

In [89]:
X_train_transformed = np.concatenate((X_train_rem,X_train_age,X_train_sex,X_train_embarked),axis=1)
X_test_transformed = np.concatenate((X_test_rem,X_test_age,X_test_sex,X_test_embarked),axis=1)

In [90]:
X_test_transformed.shape

(84, 10)

In [92]:
clf = DecisionTreeClassifier()
clf.fit(X_train_transformed,y_train)

DecisionTreeClassifier()

In [93]:
y_pred = clf.predict(X_test_transformed)
y_pred

array([0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0,
       1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0,
       0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1])

In [94]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

1.0

In [97]:
import os

os.makedirs("models", exist_ok=True)

In [100]:
import pickle
pickle.dump(ohe_sex,open('models/ohe_sex.pkl','wb'))
pickle.dump(ohe_embarked,open('models/ohe_embarked.pkl','wb'))
pickle.dump(clf,open('models/clf.pkl','wb'))

In [101]:
import os

print(os.getcwd())

C:\Users\DELL